### PR TITLE
Fix typo in END_WITHOUT_START_TAG

### PR DESCRIPTION
**Pull request by wiibaa**
Trying to help moving PR https://github.com/elastic/logstash-contrib/pull/92 using
````
curl -L -s https://github.com/elastic/logstash-contrib/pull/92.patch | git am --3way
````
Moved from https://github.com/elastic/logstash-contrib/pull/92/files

hoping @knoxilla already signed the CLA ;)

### CODE REVIEW

**Comment by wiibaa** [comment]
@purbon @suyograo is it the way to go for migrating/finalizing old PRs ? also is the CLA check enabled in plugin repo ?

**Comment by purbon** [comment]
I'm investigating the CLA check, in my opinion it should be activated also here, but I'm not sure why is not (as it seems).

This way to migrate PR is perfectly ok for me.

**Comment by wiibaa** [comment]
This PR has now a **x4 merge-me bonus** through open related items 
* #6 
* https://github.com/elastic/logstash/issues/3058
* https://github.com/elastic/logstash-contrib/pull/92

**Comment by jsvd** [comment]
No cla signage by @knoxilla :(

**Comment by wiibaa** [comment]
@jsvd then what about #6 then I would only keep my commit on the spec

**Comment by wiibaa** [comment]
@jsvd I put together my commit and the commit of @frots from #6 as the CLA looks good there. so any  testing before merging would not comply.

**Comment by jsvd** [comment]
LGTM

**Comment by jsvd** [comment]
Thanks @wiibaa :+1:

**Pull request closed without merging**
